package com.example.demo.event;

public enum EventType {

    TYPE_GOODS_RECEIVE_HEADER,
    TYPE_GOODS_RECEIVE_DETAIL_CHECK,
    TYPE_GOODS_ISSUE_HEADER_CREATE,
    TYPE_GOODS_ISSUE_HEADER_GET,
    TYPE_GOODS_ISSUE_DETAIL_CHECK,
    TYPE_GOODS_ISSUE_HEADER_DELETE,
    TYPE_GOODS_RECEIVE_DETAIL,
    TYPE_GOODS_RECEIVE_DETAIL_CHECK_QUANTITY,
    TYPE_PRODUCT,
    TYPE_PRODUCT_GOODS_ISSUE,
    TYPE_SUPPLIER,
    TYPE_WAREHOUSE2,
    TYPE_WAREHOUSE,
    TYPE_WAREHOUSE_LIST,
    TYPE_SUPPLIER_LIST,
    TYPE_INVENTORY

}
